### ISSUE TITLE
Not able to see Assets with Lightweight Shader on Phone VR (Cardboard , Daydream and Gear VR)

### ISSUE THREAD

**Issue by Noob-Vulcan** [Unity-Technologies/ScriptableRenderPipeline#1304]
Hi ,

I just tried to test a scene using Lightweight RP for VR , but i'm not able to see those assets which have LightWeight shader on them .

Tried  the build with cardboard , daydream and gear vr too  , but getting same result

**Comment by robbiesri** [comment]
The XR support for Lightweight is Single-pass Stereo only. Are you using Single-pass?

**Comment by Noob-Vulcan** [comment]
Yes , i'm using Single Pass ..PFA
![screen shot 2018-05-05 at 4 02 24 pm](https://user-images.githubusercontent.com/13568651/39662352-dda92686-507d-11e8-8779-bc999f5ebb5b.png)
![screen shot 2018-05-05 at 4 01 40 pm](https://user-images.githubusercontent.com/13568651/39662354-ddd47656-507d-11e8-84eb-18f11e6ed416.png)
![screen shot 2018-05-05 at 4 01 21 pm](https://user-images.githubusercontent.com/13568651/39662355-ddff46ba-507d-11e8-850a-027ea28593da.png)

**Comment by robbiesri** [comment]
I just saw #1316. Does the scene render on your phones w/ VR disabled?

**Comment by robbiesri** [comment]
and #1318 popped up.  I wonder if this has something to do with some new shader bits...

**Comment by sebastienlagarde** [comment]
@phi-lira any though?

**Comment by Noob-Vulcan** [comment]
And i found something else .. I tried on few other phones (One Plus 5t , Lenovo zuk 2 , Google Pixel) with the below settings ....
![screen shot 2018-05-07 at 2 56 24 pm](https://user-images.githubusercontent.com/13568651/39695119-1606e196-5207-11e8-820c-a1522c1901df.png)


and i found that only Google pixel was able to run the application (Though couldn't see the LW Shader objects ) and in other phones couldn't see anything not even Unity logo , all was black (could see the VR spilt screen)

**Comment by developer6dlab** [comment]
I have the same trouble. I tryed to Build for cardboard using Unity 2018 with shadergraph. I tryed lot of ways to do that. I can build for cardboard using Unity 2018 (without shadergraph) but no more

**Comment by phi-lira** [comment]
Hey all. We are looking into a fix for this. There's an issue in the SRP shader api that is affecting multiview and single pass on adroid.

**Comment by mgeorgedeveloper** [comment]
@phi-lira what is the best way to get an eventual fix? Will an update automatically appear within the Package Manager in Unity? I just updated 1.1.5-preview, so shall I keep an eye out for a newer version soon?

**Comment by anilu221** [comment]
I tried it with the Oculus Go, I have a scene with a cube on the ground that uses a graph shader , whenever I try to look down at the cube the screen goes black, but if i look up or anywhere on the scene where the cube is not visible, the screen works normal.

**Comment by phi-lira** [comment]
Fixed in the following PR #1350 This will be backported to 2018.1 soon. 

@mgeorgedeveloper We are looking into generating a new package for 2018.2 this week. 
for 2018.1 backport it should be also a new package available soon. It will appear automatically in the Package Manager. 

@anilu221 Amplify lit shaders don't work with LWRP due to diff light constant setup. LWRP works with ShaderGraph. Does that help you?

**Comment by anilu221** [comment]
Could someone make it work with the new release?

**Comment by phi-lira** [comment]
@anilu221 It requires engine changes. An update on Amplify. They already ported to LWRP so it should be working.

**Comment by anilu221** [comment]
@phi-lira Thanks, I decided to try to do everything with the shader graph instead of amplify, but the shaders still don't render on Oculus Go when I switch to the LWRP 1.1.5. I haven't had much time to work on it and to test around different options, so maybe I'm missing something or I'm doing something wrong.

I'm working on Unity 2018 1.1.f1 with the Core & LWRP 1.1.5 and the newest package of Oculus Utilities

**Comment by mgeorgedeveloper** [comment]
@phi-lira @anilu221 I still get black screen only. This is with 1.1.5, which is the same version that's been there since before this discussion started... so, I'm just checking daily for a 1.1.6?

**Comment by phi-lira** [comment]
@anilu221 @mgeorgedeveloper 
 - Currently there's only a fix for 2018.2 beta. The only way to get it now is to get SRP from github master. Follow the instructions here to do it: https://gist.github.com/phi-lira/7bc0109a3bbb2bc2ef132cd05bb26f14
 - We are generating a new package for 2018.2 tomorrow. Sorry for the delay. 
 - For 18.1 we are in the process of backporting it but since this requires Unity changes it requires a patch update to 18.1 and a PR backport on C# side (which is ready waiting for the C++ counterpart)
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/1360

**Comment by anilu221** [comment]
@phi-lira I'll try it on the next 2018.2 package, Thanks a lot!!

**Comment by anilu221** [comment]
@phi-lira I just downloaded 2018.2.0b5 and installed the SRP Core 1.1.8 and the LWRP 1.1.8, but still doesn't work. I get a similar problem than @mgeorgedeveloper the skybox renders but the objects with SRP shaders don't

**Comment by mgeorgedeveloper** [comment]
@anilu221 I think we're waiting for the next package after 1.1.8. I'm checking daily, should be here soon I hope.

**Comment by AlexandreFiset** [comment]
"We are generating a new package for 2018.2 tomorrow. Sorry for the delay."

As of 05/29, everything render black on Oculus Go with 2018.2 and LWRP.

**Comment by djuniah** [comment]
Just tested on 2018.2.0b8 and the latest SRP code from this repo and the issue is still present.

**Comment by phi-lira** [comment]
@brandon-unity3d Do you have any clues here?

**Comment by phi-lira** [comment]
If you disable PostFX and MSAA do you still have this issue on 2.0.3-preview?

**Comment by djuniah** [comment]
I can confirm that disabling MSAA got it working on the Oculus GO
