### ISSUE TITLE
Posteffects not working in VR with LWRP

### ISSUE THREAD

**Issue by julhe** [Unity-Technologies/ScriptableRenderPipeline#1317]
Title says all. Its working fine in the scene view, but not in-game. 😟

**Comment by sebastienlagarde** [comment]
Psotprocess are not supported with VR (iirc - cc @Chman)

**Comment by Chman** [comment]
Post-processes do work in VR with the standard pipeline, in multi-pass and single-pass non instanced. Make sure you're not running single-pass instanced. Aside from that, I'm not sure what the current support for VR is in LWRP.

**Comment by Chman** [comment]
Btw, what's your target platform?

**Comment by julhe** [comment]
Currently Windows with OpenVR. Maybe PS-VR in the future. I use Single-Pass rendering. BTW: is this supposed to be? 
![grafik](https://user-images.githubusercontent.com/18037091/39693977-0811a952-51e6-11e8-81e9-7894c0a35f63.png)

**Comment by Chman** [comment]
Nope, looks like it's hardcoded in LWRP. It shouldn't be anymore. cc @phi-lira

**Comment by phi-lira** [comment]
I tested recently and there was still an issue with PostFX and LWRP. That's why it was forcebly to be disable. I'm trying to get someone from VR team to take a look at it.

**Comment by equalsequals** [comment]
@phi-lira

Im curious what issues are you observing? I've made modifications to my local branch of LWRP and managed to get PPSv2 working in VR (FXAA, Bloom, and Color Correction, specifically) which look correct in my testbed.

**Comment by phi-lira** [comment]
Fixed in #1618 and the counter part PR on PostProcessing github. Thanks for the @equalsequals for the solution.

**Comment by Tossrock** [comment]
That commit is tagged 3.0.0-preview, but when I upgrade my LWRP package to 3.0.0-preview, bloom still doesn't work in VR. Did this not actually make it into the 3.0.0-preview release?
